### ISSUE TITLE
About memory

### ISSUE THREAD

**Issue by Heisenberg-Yin** [sunilkmaurya/FSGNN#1]
I meet memory problem When I do the pre-process for ogbn-papers100M, could tell me how much memory does it need?

**Comment by sunilkmaurya** [comment]
Hi! Thanks for your interest in our work. I used a machine with 400+GB memory to preprocess the dataset. At the time I didn't measure exact memory usage. The ogb dataloader itself can take roughly up to 80GB of memory to load the dataset (ogbn-papers100M), and further preprocessing will require more memory. So it might take few hundred GBs of total memory. The preprocessing script is not memory-optimized, as all intermediate results are stored in the memory. You can modify it to save intermediate results to disk and load it back when required. It may increase the preprocessing time, but will reduce overall memory requirements. I will update the script to use less memory sometime later.

Alternatively, I am preparing to upload and share the preprocessed data splits soon. You can directly use those to train the model without needing large amount of memory. Please wait for a while if you would like to use those splits directly.
