### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by Affan-Abbas8** [sunilkmaurya/FSGNN#3]
Brother, can you plz tell me any simple (as I am not much proficient in coding) future direction for this work??
I need to improve the results a bit.

**Comment by sunilkmaurya** [comment]
Hi! Thanks for your interest in our work. It would be difficult to suggest anything without doing some amount of experiments. Simplest way would be to increase hidden dimensions. This may or may not work. More up to date results on these datasets are here: https://paperswithcode.com/task/node-classification .

**Comment by Affan-Abbas8** [comment]
thanks for your response.
