### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by Affan-Abbas8** [sunilkmaurya/FSGNN#4]
Hi,
What are hops in your paper??

**Comment by Affan-Abbas8** [comment]
The experimentation I have done on your paper are as follows:

• I tried around 8-10 optimizers
• Changed the learning rates
• Added skip connections
• Added early stopping
• Added/removed layers
- Plus changed activation functions.

but the improvement is very less (within 0.5 % in accuracy).
any other way to improve your paper??

**Comment by sunilkmaurya** [comment]
Hi, 
Thanks for your interest in our work.
We have 3 & 8 hops in main results and 16 & 32 hops in additional results to show that
over-smoothing can be avoided.

If you are getting improvements up to 0.5%, I think they are not as bad as you think. Getting
significant improvements in results without changing the approach could be difficult. If some
common factor in your experiments is getting you better results on multiple datasets, then it 
could be an interesting finding.

I have added a file `accuracy_multiple_settings.pdf` containing exploratory results in our paper.
You can see increasing hidden dimensions leads to improvements in accuracy on most datasets.

**Comment by Affan-Abbas8** [comment]
> Hi, Thanks for your interest in our work. We have 3 & 8 hops in main results and 16 & 32 hops in additional results to show that over-smoothing can be avoided.
> 
> If you are getting improvements up to 0.5%, I think they are not as bad as you think. Getting significant improvements in results without changing the approach could be difficult. If some common factor in your experiments is getting you better results on multiple datasets, then it could be an interesting finding.
> 
> I have added a file `accuracy_multiple_settings.pdf` containing exploratory results in our paper. You can see increasing hidden dimensions leads to improvements in accuracy on most datasets.

Thanks for your response
God bless you!
