### ISSUE TITLE
help needed sir

### ISSUE THREAD

**Issue by Affanabbbas** [sunilkmaurya/FSGNN#6]
For attention mechanism, each node must be given an attention score. We need to find node classification accuracy for Graph attention layers. But it is the input of 2 parameters:
1) Node features
2) Adj- Matrics/edge list

We are unable to find the adj list in your FSGNN code. What have you named it in the code?

and can we improve the results by applying an attention mechanism to your code??
your kind suggestion is needed

**Comment by sunilkmaurya** [comment]
Hi, 
In the code, adjacency matrix is generated from a NetworkX graph. For example, line 143 in `process.py`. You can also generate adjacency list from the same graph.

**Comment by Affanabbbas** [comment]
thank you!
