### ISSUE TITLE
help needed!

### ISSUE THREAD

**Issue by Affanabbbas** [sunilkmaurya/FSGNN#7]
Can I get the code to visualize your paper's results??
If so, Plz share it on affan_abbas8@yahoo.com
thank you!

**Comment by sunilkmaurya** [comment]
Hi,
If you mean embedding visualization, you can do it as following:
1. Train the model and during the inference mode save the embeddings for all nodes or as you would like.
2. Using sklearn TSNE, reduce the dimensionality to 2 by setting n_components.
3. Using matplotlib/seaborn, you can plot the 2-dimensional embedding with node labels as colors.

**Comment by Affanabbbas** [comment]
okay thnks
