### ISSUE TITLE
help needed. your prompt response will be highly appreciated!

### ISSUE THREAD

**Issue by Affanabbbas** [sunilkmaurya/FSGNN#8]
Hi brother.
I have some ideas to improve your paper results but not sure will they work or not.
Can you plz tell that will adding:

1) Multihead attention mechanism
2) Skip connections
3) Early stopping
4) Changing depth

will any of these, improve the results?

**Comment by Affanabbbas** [comment]
and there is a minor drop in the performance when I try to reproduce your code's results. Can it be possibly due to a change of CUDA version, Python version, or Pytorch version??
and I am using google colab for the experimentation.

**Comment by Affanabbbas** [comment]
Or working with different layers or models could improve the results?

**Comment by sunilkmaurya** [comment]
Hi,
I think the options you mentioned have already been used in other works one way or the other.  It is hard to predict their impact on the performance without actually running the experiments. There are newer models that have better results. You can view SOTA results here https://paperswithcode.com/task/node-classification, and check out corresponding papers for the ideas.

What you are observing is expected. With different CUDA, PyTorch version or GPU, the performance of the model for a set of hyperparameters can change (Please check my related comment in Readme).  You might need to do a bit hyperparameter tuning to get back the similar performance on a different platform.

**Comment by Affanabbbas** [comment]
okay
Thanks a lot for your reply.
God bless you!
